apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-multitool
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        command: ["sh", "-c", "tail -f /var/log/syslog"]
        volumeMounts:
        - name: syslog
          mountPath: /var/log
      volumes:
      - name: syslog
        hostPath:
          path: /var/log
          type: Directory