apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["sh", "-c", 'while true; do echo $(date +%d-%m-%Y\ %H:%M:%S) - Привет, Дмитрий, пишу тебе из контейнера busybox! >> /input/description.txt; sleep 5; done']


        volumeMounts:
        - name: my-volume
          mountPath: /input
      - name: multitool
        image: wbitt/network-multitool:latest
        command: ["sh", "-c", "tail -f /output/description.txt"]
        volumeMounts:
        - name: my-volume
          mountPath: /output
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "1180"
      volumes:
        - name: my-volume
          emptyDir: {}

