apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-port
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool-port
      protocol: TCP
      port: 9002
      targetPort: 8080
      nodePort: 30002
  type: NodePort