apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: multitools
        image: wbitt/network-multitool:openshift
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-svc
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: nginx-https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: multitool-http
    port: 1180
    protocol: TCP
    targetPort: 1180
  - name: multitool-https
    port: 11443
    protocol: TCP
    targetPort: 11443
