apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool:latest
    env:
    - name: HTTP_PORT
      value: "1080"
    - name: HTTPS_PORT
      value: "10443"
    ports:
    - containerPort: 1080
      name: http-port
    - containerPort: 10443
      name: https-port