#role-binding.yaml

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dmlorren-rb
subjects:
- kind: User
  name: dmlorren
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dmlorren-role
  apiGroup: rbac.authorization.k8s.io